In [16]:
import pandas as pd
compras_csv = pd.read_csv('D:/Users/Eugenia/Documents/Facus/3 ano/Computacion I/supermercado_ej/COMPRAS_supermercado.csv')
view_csv = compras_csv.head()  
view_csv

   PRSUC PRCOD       PRFEC  PRPROV  PRCANT   PRPRE
0  SUC01  P100  2025-01-01  PROV02     116  246.97
1  SUC01  P100  2025-01-05  PROV13     103  255.53
2  SUC01  P100  2025-01-09  PROV04     112  254.78
3  SUC01  P100  2025-01-09  PROV04      63  262.24
4  SUC01  P100  2025-01-15  PROV03     101  254.72

Enunciado: 

En un supermercado de la Ciudad se desea obtener una estadística de las compras realizadas en
un período de tiempo en las diferentes sucursales que posee. La información se encuentra
almacenada en un archivo COMPRAS cuyo formato de registro es el siguiente (archivo csv):
SUCURSAL (PRSUC)
CODIGO DE PRODUCTO (PRCOD)
FECHA DE COMPRA (PRFEC)
PROVEEDOR (PRPROV)
CANTIDAD COMPRADA (PRCANT)
PRECIO UNITARIO COMPRA (PRPRE)

La información se encuentra ordenada por código de sucursal, producto, fecha de compra y
proveedor.
Se debe obtener información sobre:
a) POR PRODUCTO: De cada producto comprado en cada sucursal indicar el total comprado
en unidades (TOTUNI) y en pesos (TOTPES)
b) POR SUCURSAL: l informar el total comprado en unidades (TOTSUC) y el producto de
mayor (MYPROD, MYIMPOR) y menor compra (MNPRO,MNIMPOR) en pesos.
c) Por otro lado indicar a nivel total: total de sucursales del supermercado (CANSUC) y
compra total en pesos de todas las sucursales (TOTALIMP)

Imprimir los resultados obtenidos.

1-a) POR PRODUCTO: De cada producto comprado en cada sucursal indicar el total comprado
en unidades (TOTUNI) y en pesos (TOTPES)

In [32]:
compras_csv['IMPORTE_TOTAL'] = compras_csv['PRPRE'] * compras_csv['PRCANT']
compras_csv.groupby(['PRSUC','PRCOD']).agg(tot_uni=('PRCANT','sum'), tot_imp=('IMPORTE_TOTAL','sum')).reset_index()

     PRSUC PRCOD  tot_uni     tot_imp
0    SUC01  P100     4015  1063022.53
1    SUC01  P101     2779  1051903.95
2    SUC01  P102     2063  1052493.76
3    SUC01  P103     2785  1648188.13
4    SUC01  P104     2712  2088022.61
..     ...   ...      ...         ...
395  SUC10  P135      194   381739.38
396  SUC10  P136      335   579756.86
397  SUC10  P137      172   358252.83
398  SUC10  P138      545   392898.36
399  SUC10  P139      125   371742.00

[400 rows x 4 columns]

In [29]:
i = 0
n = len(compras_csv)
while i < n: 
    Sucursal = compras_csv.loc[i, 'PRSUC']
    Producto = compras_csv.loc[i, 'PRCOD']

    totuni = 0 
    totpeso = 0 
    while i < n and compras_csv.loc[i, 'PRSUC'] == Sucursal and compras_csv.loc[i, 'PRCOD'] == Producto:
        totuni += compras_csv.loc[i, 'PRCANT']
        totpeso += compras_csv.loc[i, 'PRCANT'] * compras_csv.loc[i, 'PRPRE']
        i += 1
    print(f'Sucursal: {Sucursal}, Producto: {Producto}, Total Unidades: {totuni}, Total en pesos: ${totpeso}')

Sucursal: SUC01, Producto: P100, Total Unidades: 4015, Total en pesos: $1063022.53
Sucursal: SUC01, Producto: P101, Total Unidades: 2779, Total en pesos: $1051903.95
Sucursal: SUC01, Producto: P102, Total Unidades: 2063, Total en pesos: $1052493.7600000002
Sucursal: SUC01, Producto: P103, Total Unidades: 2785, Total en pesos: $1648188.1299999997
Sucursal: SUC01, Producto: P104, Total Unidades: 2712, Total en pesos: $2088022.6099999999
Sucursal: SUC01, Producto: P105, Total Unidades: 2489, Total en pesos: $1902345.3500000003
Sucursal: SUC01, Producto: P106, Total Unidades: 2398, Total en pesos: $2238944.6100000003
Sucursal: SUC01, Producto: P107, Total Unidades: 2895, Total en pesos: $2902189.4699999993
Sucursal: SUC01, Producto: P108, Total Unidades: 605, Total en pesos: $614157.0700000002
Sucursal: SUC01, Producto: P109, Total Unidades: 948, Total en pesos: $1003512.6499999999
Sucursal: SUC01, Producto: P110, Total Unidades: 1096, Total en pesos: $1313691.9800000002
Sucursal: SUC01, Producto: P111, Total Unidades: 1116, Total en pesos: $1281715.32
Sucursal: SUC01, Producto: P112, Total Unidades: 881, Total en pesos: $1250955.61
Sucursal: SUC01, Producto: P113, Total Unidades: 1190, Total en pesos: $1484639.8100000003
Sucursal: SUC01, Producto: P114, Total Unidades: 841, Total en pesos: $1380695.9700000002
Sucursal: SUC01, Producto: P115, Total Unidades: 1012, Total en pesos: $1114421.7399999998
Sucursal: SUC01, Producto: P116, Total Unidades: 504, Total en pesos: $755060.46
Sucursal: SUC01, Producto: P117, Total Unidades: 1065, Total en pesos: $2098615.27
Sucursal: SUC01, Producto: P118, Total Unidades: 608, Total en pesos: $1066226.2100000002
Sucursal: SUC01, Producto: P119, Total Unidades: 809, Total en pesos: $1708845.18
Sucursal: SUC01, Producto: P120, Total Unidades: 923, Total en pesos: $1486815.94
Sucursal: SUC01, Producto: P121, Total Unidades: 925, Total en pesos: $1660782.84
Sucursal: SUC01, Producto: P122, Total Unidades: 1194, Total en pesos: $2051821.6000000003
Sucursal: SUC01, Producto: P123, Total Unidades: 880, Total en pesos: $1843952.42
Sucursal: SUC01, Producto: P124, Total Unidades: 1143, Total en pesos: $2817349.31
Sucursal: SUC01, Producto: P125, Total Unidades: 798, Total en pesos: $2356655.1299999994
Sucursal: SUC01, Producto: P126, Total Unidades: 899, Total en pesos: $2474869.14
Sucursal: SUC01, Producto: P127, Total Unidades: 1236, Total en pesos: $3162432.18
Sucursal: SUC01, Producto: P128, Total Unidades: 784, Total en pesos: $1917402.0300000003
Sucursal: SUC01, Producto: P129, Total Unidades: 575, Total en pesos: $1862498.5
Sucursal: SUC01, Producto: P130, Total Unidades: 823, Total en pesos: $1654525.4099999997
Sucursal: SUC01, Producto: P131, Total Unidades: 1105, Total en pesos: $3213342.73
Sucursal: SUC01, Producto: P132, Total Unidades: 350, Total en pesos: $494923.38
Sucursal: SUC01, Producto: P133, Total Unidades: 238, Total en pesos: $465853.4
Sucursal: SUC01, Producto: P134, Total Unidades: 142, Total en pesos: $320703.71
Sucursal: SUC01, Producto: P135, Total Unidades: 344, Total en pesos: $495946.99
Sucursal: SUC01, Producto: P136, Total Unidades: 183, Total en pesos: $397868.41000000003
Sucursal: SUC01, Producto: P137, Total Unidades: 377, Total en pesos: $468536.3000000001
Sucursal: SUC01, Producto: P138, Total Unidades: 554, Total en pesos: $669473.8200000001
Sucursal: SUC01, Producto: P139, Total Unidades: 95, Total en pesos: $382187.83
Sucursal: SUC02, Producto: P100, Total Unidades: 1964, Total en pesos: $513656.52999999997
Sucursal: SUC02, Producto: P101, Total Unidades: 1901, Total en pesos: $709471.9499999998
Sucursal: SUC02, Producto: P102, Total Unidades: 1989, Total en pesos: $1017013.0299999999
Sucursal: SUC02, Producto: P103, Total Unidades: 1447, Total en pesos: $837812.7200000001
Sucursal: SUC02, Producto: P104, Total Unidades: 1904, Total en pesos: $1449893.51
Sucursal: SUC02, Producto: P105, Total Unidades: 2010, Total en pesos: $1430943.65
Sucursal: SUC02, Producto: P106, Total Unidades: 2371, Total en pesos: $2155968.909999999
Sucursal: SUC02, Producto: P107, Total Unidades: 1661, Total en pesos: $1542695.4999999998
Sucursal: SUC02, Producto: P108, Total Unidades: 562, Total en pesos: $504920.45
Sucursal: SUC02, Producto: P109, Total Unidades: 774, Total en pesos: $736391.43
Sucursal: SUC02, Producto: P110, Total Unidades: 418, Total en pesos: $341879.04999999993
Sucursal: SUC02, Producto: P111, Total Unidades: 927, Total en pesos: $841700.2100000002
Sucursal: SUC02, Producto: P112, Total Unidades: 683, Total en pesos: $914491.0500000003
Sucursal: SUC02, Producto: P113, Total Unidades: 922, Total en pesos: $775054.0700000001
Sucursal: SUC02, Producto: P114, Total Unidades: 597, Total en pesos: $976054.5000000001
Sucursal: SUC02, Producto: P115, Total Unidades: 694, Total en pesos: $530293.8400000001
Sucursal: SUC02, Producto: P116, Total Unidades: 673, Total en pesos: $1003916.6500000001
Sucursal: SUC02, Producto: P117, Total Unidades: 524, Total en pesos: $785135.16
Sucursal: SUC02, Producto: P118, Total Unidades: 585, Total en pesos: $983768.5100000001
Sucursal: SUC02, Producto: P119, Total Unidades: 569, Total en pesos: $1148466.9800000002
Sucursal: SUC02, Producto: P120, Total Unidades: 795, Total en pesos: $1583897.0000000005
Sucursal: SUC02, Producto: P121, Total Unidades: 701, Total en pesos: $1393822.9100000001
Sucursal: SUC02, Producto: P122, Total Unidades: 1181, Total en pesos: $1145357.44
Sucursal: SUC02, Producto: P123, Total Unidades: 457, Total en pesos: $711721.92
Sucursal: SUC02, Producto: P124, Total Unidades: 542, Total en pesos: $871818.2800000001
Sucursal: SUC02, Producto: P125, Total Unidades: 241, Total en pesos: $634456.3300000001
Sucursal: SUC02, Producto: P126, Total Unidades: 847, Total en pesos: $1975763.08
Sucursal: SUC02, Producto: P127, Total Unidades: 1175, Total en pesos: $1797447.72
Sucursal: SUC02, Producto: P128, Total Unidades: 731, Total en pesos: $1636480.11
Sucursal: SUC02, Producto: P129, Total Unidades: 392, Total en pesos: $1233540.3599999999
Sucursal: SUC02, Producto: P130, Total Unidades: 609, Total en pesos: $1709195.29
Sucursal: SUC02, Producto: P131, Total Unidades: 357, Total en pesos: $849326.4600000001
Sucursal: SUC02, Producto: P132, Total Unidades: 248, Total en pesos: $285076.69000000006
Sucursal: SUC02, Producto: P133, Total Unidades: 282, Total en pesos: $298629.96
Sucursal: SUC02, Producto: P134, Total Unidades: 91, Total en pesos: $133580.52999999997
Sucursal: SUC02, Producto: P135, Total Unidades: 474, Total en pesos: $392003.84
Sucursal: SUC02, Producto: P136, Total Unidades: 225, Total en pesos: $331404.37
Sucursal: SUC02, Producto: P137, Total Unidades: 57, Total en pesos: $101367.04
Sucursal: SUC02, Producto: P138, Total Unidades: 361, Total en pesos: $447383.0800000001
Sucursal: SUC02, Producto: P139, Total Unidades: 170, Total en pesos: $468735.24
Sucursal: SUC03, Producto: P100, Total Unidades: 3092, Total en pesos: $822121.3600000001
Sucursal: SUC03, Producto: P101, Total Unidades: 2975, Total en pesos: $1130535.3199999996
Sucursal: SUC03, Producto: P102, Total Unidades: 3400, Total en pesos: $1734668.4200000002
Sucursal: SUC03, Producto: P103, Total Unidades: 3435, Total en pesos: $2059999.6900000004
Sucursal: SUC03, Producto: P104, Total Unidades: 2790, Total en pesos: $2156842.2500000005
Sucursal: SUC03, Producto: P105, Total Unidades: 2906, Total en pesos: $2191256.19
Sucursal: SUC03, Producto: P106, Total Unidades: 3726, Total en pesos: $3427691.439999999
Sucursal: SUC03, Producto: P107, Total Unidades: 3100, Total en pesos: $3180598.7
Sucursal: SUC03, Producto: P108, Total Unidades: 681, Total en pesos: $619655.8100000002
Sucursal: SUC03, Producto: P109, Total Unidades: 456, Total en pesos: $441953.08999999997
Sucursal: SUC03, Producto: P110, Total Unidades: 653, Total en pesos: $658106.7599999999
Sucursal: SUC03, Producto: P111, Total Unidades: 1398, Total en pesos: $1265073.5
Sucursal: SUC03, Producto: P112, Total Unidades: 750, Total en pesos: $967793.62
Sucursal: SUC03, Producto: P113, Total Unidades: 722, Total en pesos: $768165.41
Sucursal: SUC03, Producto: P114, Total Unidades: 554, Total en pesos: $611742.69
Sucursal: SUC03, Producto: P115, Total Unidades: 1239, Total en pesos: $1831816.01
Sucursal: SUC03, Producto: P116, Total Unidades: 806, Total en pesos: $1288622.7699999998
Sucursal: SUC03, Producto: P117, Total Unidades: 999, Total en pesos: $1580259.6899999997
Sucursal: SUC03, Producto: P118, Total Unidades: 1014, Total en pesos: $1939738.96
Sucursal: SUC03, Producto: P119, Total Unidades: 926, Total en pesos: $1954295.75
Sucursal: SUC03, Producto: P120, Total Unidades: 894, Total en pesos: $1633258.1700000002
Sucursal: SUC03, Producto: P121, Total Unidades: 1278, Total en pesos: $2899336.249999999
Sucursal: SUC03, Producto: P122, Total Unidades: 755, Total en pesos: $1145879.38
Sucursal: SUC03, Producto: P123, Total Unidades: 969, Total en pesos: $2330104.66
Sucursal: SUC03, Producto: P124, Total Unidades: 813, Total en pesos: $1960735.5099999998
Sucursal: SUC03, Producto: P125, Total Unidades: 707, Total en pesos: $2098221.91
Sucursal: SUC03, Producto: P126, Total Unidades: 797, Total en pesos: $2046928.4300000006
Sucursal: SUC03, Producto: P127, Total Unidades: 1367, Total en pesos: $2002418.5099999998
Sucursal: SUC03, Producto: P128, Total Unidades: 595, Total en pesos: $1913688.7700000003
Sucursal: SUC03, Producto: P129, Total Unidades: 1032, Total en pesos: $3537428.3099999996
Sucursal: SUC03, Producto: P130, Total Unidades: 1148, Total en pesos: $2851141.5800000005
Sucursal: SUC03, Producto: P131, Total Unidades: 727, Total en pesos: $2167520.7199999997
Sucursal: SUC03, Producto: P132, Total Unidades: 470, Total en pesos: $571689.31
Sucursal: SUC03, Producto: P133, Total Unidades: 197, Total en pesos: $432133.7100000001
Sucursal: SUC03, Producto: P134, Total Unidades: 89, Total en pesos: $264632.85
Sucursal: SUC03, Producto: P135, Total Unidades: 221, Total en pesos: $637156.6100000001
Sucursal: SUC03, Producto: P136, Total Unidades: 258, Total en pesos: $365330.13
Sucursal: SUC03, Producto: P137, Total Unidades: 434, Total en pesos: $522836.48
Sucursal: SUC03, Producto: P138, Total Unidades: 511, Total en pesos: $486532.02
Sucursal: SUC03, Producto: P139, Total Unidades: 170, Total en pesos: $368687.9699999999
Sucursal: SUC04, Producto: P100, Total Unidades: 2296, Total en pesos: $609873.4299999999
Sucursal: SUC04, Producto: P101, Total Unidades: 1616, Total en pesos: $619922.1300000001
Sucursal: SUC04, Producto: P102, Total Unidades: 2442, Total en pesos: $1246688.31
Sucursal: SUC04, Producto: P103, Total Unidades: 2707, Total en pesos: $1584230.93
Sucursal: SUC04, Producto: P104, Total Unidades: 1556, Total en pesos: $1182533.79
Sucursal: SUC04, Producto: P105, Total Unidades: 2411, Total en pesos: $1858791.3800000001
Sucursal: SUC04, Producto: P106, Total Unidades: 2790, Total en pesos: $2545515.5199999996
Sucursal: SUC04, Producto: P107, Total Unidades: 2518, Total en pesos: $2477812.56
Sucursal: SUC04, Producto: P108, Total Unidades: 868, Total en pesos: $701191.4099999999
Sucursal: SUC04, Producto: P109, Total Unidades: 1107, Total en pesos: $1069105.11
Sucursal: SUC04, Producto: P110, Total Unidades: 435, Total en pesos: $443446.69
Sucursal: SUC04, Producto: P111, Total Unidades: 801, Total en pesos: $573586.27
Sucursal: SUC04, Producto: P112, Total Unidades: 559, Total en pesos: $645024.1300000001
Sucursal: SUC04, Producto: P113, Total Unidades: 726, Total en pesos: $673370.33
Sucursal: SUC04, Producto: P114, Total Unidades: 760, Total en pesos: $958762.19
Sucursal: SUC04, Producto: P115, Total Unidades: 638, Total en pesos: $669985.39
Sucursal: SUC04, Producto: P116, Total Unidades: 817, Total en pesos: $1306901.6099999999
Sucursal: SUC04, Producto: P117, Total Unidades: 610, Total en pesos: $964568.55
Sucursal: SUC04, Producto: P118, Total Unidades: 638, Total en pesos: $965375.7299999997
Sucursal: SUC04, Producto: P119, Total Unidades: 657, Total en pesos: $1133624.8499999999
Sucursal: SUC04, Producto: P120, Total Unidades: 548, Total en pesos: $1107561.42
Sucursal: SUC04, Producto: P121, Total Unidades: 838, Total en pesos: $1675658.5699999998
Sucursal: SUC04, Producto: P122, Total Unidades: 858, Total en pesos: $1094788.96
Sucursal: SUC04, Producto: P123, Total Unidades: 1173, Total en pesos: $1617774.7500000002
Sucursal: SUC04, Producto: P124, Total Unidades: 808, Total en pesos: $1747462.3599999999
Sucursal: SUC04, Producto: P125, Total Unidades: 461, Total en pesos: $1254115.23
Sucursal: SUC04, Producto: P126, Total Unidades: 771, Total en pesos: $1944352.6300000001
Sucursal: SUC04, Producto: P127, Total Unidades: 1234, Total en pesos: $1446934.13
Sucursal: SUC04, Producto: P128, Total Unidades: 641, Total en pesos: $1501692.1799999997
Sucursal: SUC04, Producto: P129, Total Unidades: 614, Total en pesos: $1915936.0699999998
Sucursal: SUC04, Producto: P130, Total Unidades: 409, Total en pesos: $1254183.38
Sucursal: SUC04, Producto: P131, Total Unidades: 876, Total en pesos: $2156473.0900000003
Sucursal: SUC04, Producto: P132, Total Unidades: 342, Total en pesos: $343080.19999999995
Sucursal: SUC04, Producto: P133, Total Unidades: 402, Total en pesos: $649277.5999999999
Sucursal: SUC04, Producto: P134, Total Unidades: 78, Total en pesos: $253937.79
Sucursal: SUC04, Producto: P135, Total Unidades: 212, Total en pesos: $406318.56999999995
Sucursal: SUC04, Producto: P136, Total Unidades: 297, Total en pesos: $420732.0
Sucursal: SUC04, Producto: P137, Total Unidades: 258, Total en pesos: $181337.28999999998
Sucursal: SUC04, Producto: P138, Total Unidades: 644, Total en pesos: $378570.58
Sucursal: SUC04, Producto: P139, Total Unidades: 110, Total en pesos: $301107.55999999994
Sucursal: SUC05, Producto: P100, Total Unidades: 2083, Total en pesos: $546214.7900000002
Sucursal: SUC05, Producto: P101, Total Unidades: 2101, Total en pesos: $785716.9200000002
Sucursal: SUC05, Producto: P102, Total Unidades: 1865, Total en pesos: $941796.53
Sucursal: SUC05, Producto: P103, Total Unidades: 1842, Total en pesos: $1091460.25
Sucursal: SUC05, Producto: P104, Total Unidades: 1762, Total en pesos: $1327170.5399999998
Sucursal: SUC05, Producto: P105, Total Unidades: 3066, Total en pesos: $2001715.1499999997
Sucursal: SUC05, Producto: P106, Total Unidades: 1814, Total en pesos: $1665641.6599999997
Sucursal: SUC05, Producto: P107, Total Unidades: 1433, Total en pesos: $1406907.8599999999
Sucursal: SUC05, Producto: P108, Total Unidades: 727, Total en pesos: $619259.1799999998
Sucursal: SUC05, Producto: P109, Total Unidades: 560, Total en pesos: $511729.4799999999
Sucursal: SUC05, Producto: P110, Total Unidades: 495, Total en pesos: $538267.4199999999
Sucursal: SUC05, Producto: P111, Total Unidades: 1016, Total en pesos: $655844.8
Sucursal: SUC05, Producto: P112, Total Unidades: 594, Total en pesos: $749224.3099999999
Sucursal: SUC05, Producto: P113, Total Unidades: 802, Total en pesos: $662118.7999999999
Sucursal: SUC05, Producto: P114, Total Unidades: 736, Total en pesos: $1028239.4400000002
Sucursal: SUC05, Producto: P115, Total Unidades: 443, Total en pesos: $625746.73
Sucursal: SUC05, Producto: P116, Total Unidades: 424, Total en pesos: $449301.0899999999
Sucursal: SUC05, Producto: P117, Total Unidades: 470, Total en pesos: $856713.2400000001
Sucursal: SUC05, Producto: P118, Total Unidades: 720, Total en pesos: $1260629.5799999998
Sucursal: SUC05, Producto: P119, Total Unidades: 681, Total en pesos: $1435843.4300000002
Sucursal: SUC05, Producto: P120, Total Unidades: 651, Total en pesos: $1215738.3100000003
Sucursal: SUC05, Producto: P121, Total Unidades: 896, Total en pesos: $1658193.7100000004
Sucursal: SUC05, Producto: P122, Total Unidades: 818, Total en pesos: $1759672.6099999999
Sucursal: SUC05, Producto: P123, Total Unidades: 1001, Total en pesos: $1365196.22
Sucursal: SUC05, Producto: P124, Total Unidades: 671, Total en pesos: $1530716.0499999998
Sucursal: SUC05, Producto: P125, Total Unidades: 379, Total en pesos: $1047176.6299999999
Sucursal: SUC05, Producto: P126, Total Unidades: 445, Total en pesos: $1366512.08
Sucursal: SUC05, Producto: P127, Total Unidades: 930, Total en pesos: $1727942.03
Sucursal: SUC05, Producto: P128, Total Unidades: 539, Total en pesos: $1462642.73
Sucursal: SUC05, Producto: P129, Total Unidades: 547, Total en pesos: $1873821.0199999998
Sucursal: SUC05, Producto: P130, Total Unidades: 892, Total en pesos: $2295032.91
Sucursal: SUC05, Producto: P131, Total Unidades: 792, Total en pesos: $2003758.4599999995
Sucursal: SUC05, Producto: P132, Total Unidades: 294, Total en pesos: $308394.51000000007
Sucursal: SUC05, Producto: P133, Total Unidades: 78, Total en pesos: $146891.51
Sucursal: SUC05, Producto: P134, Total Unidades: 94, Total en pesos: $243299.83999999997
Sucursal: SUC05, Producto: P135, Total Unidades: 227, Total en pesos: $380230.95
Sucursal: SUC05, Producto: P136, Total Unidades: 119, Total en pesos: $266442.17
Sucursal: SUC05, Producto: P137, Total Unidades: 296, Total en pesos: $204718.87999999998
Sucursal: SUC05, Producto: P138, Total Unidades: 695, Total en pesos: $452184.4000000001
Sucursal: SUC05, Producto: P139, Total Unidades: 127, Total en pesos: $307806.99
Sucursal: SUC06, Producto: P100, Total Unidades: 1665, Total en pesos: $434402.20000000007
Sucursal: SUC06, Producto: P101, Total Unidades: 1243, Total en pesos: $465665.42000000004
Sucursal: SUC06, Producto: P102, Total Unidades: 1628, Total en pesos: $840720.38
Sucursal: SUC06, Producto: P103, Total Unidades: 1440, Total en pesos: $841204.0399999999
Sucursal: SUC06, Producto: P104, Total Unidades: 1847, Total en pesos: $1426299.7700000003
Sucursal: SUC06, Producto: P105, Total Unidades: 1837, Total en pesos: $1240423.3399999999
Sucursal: SUC06, Producto: P106, Total Unidades: 1681, Total en pesos: $1495357.55
Sucursal: SUC06, Producto: P107, Total Unidades: 2220, Total en pesos: $2153347.7299999995
Sucursal: SUC06, Producto: P108, Total Unidades: 697, Total en pesos: $551338.7100000001
Sucursal: SUC06, Producto: P109, Total Unidades: 617, Total en pesos: $580933.2899999999
Sucursal: SUC06, Producto: P110, Total Unidades: 454, Total en pesos: $463655.53
Sucursal: SUC06, Producto: P111, Total Unidades: 821, Total en pesos: $727844.18
Sucursal: SUC06, Producto: P112, Total Unidades: 720, Total en pesos: $849245.86
Sucursal: SUC06, Producto: P113, Total Unidades: 907, Total en pesos: $891859.1600000001
Sucursal: SUC06, Producto: P114, Total Unidades: 691, Total en pesos: $851584.4800000001
Sucursal: SUC06, Producto: P115, Total Unidades: 909, Total en pesos: $1018515.1199999998
Sucursal: SUC06, Producto: P116, Total Unidades: 736, Total en pesos: $1017201.11
Sucursal: SUC06, Producto: P117, Total Unidades: 864, Total en pesos: $1317812.2600000002
Sucursal: SUC06, Producto: P118, Total Unidades: 516, Total en pesos: $770351.97
Sucursal: SUC06, Producto: P119, Total Unidades: 727, Total en pesos: $1478971.3900000004
Sucursal: SUC06, Producto: P120, Total Unidades: 555, Total en pesos: $1147662.94
Sucursal: SUC06, Producto: P121, Total Unidades: 780, Total en pesos: $1464092.3299999996
Sucursal: SUC06, Producto: P122, Total Unidades: 747, Total en pesos: $873901.71
Sucursal: SUC06, Producto: P123, Total Unidades: 838, Total en pesos: $1484280.5899999999
Sucursal: SUC06, Producto: P124, Total Unidades: 328, Total en pesos: $856675.2700000001
Sucursal: SUC06, Producto: P125, Total Unidades: 678, Total en pesos: $2004103.6400000001
Sucursal: SUC06, Producto: P126, Total Unidades: 763, Total en pesos: $1629967.46
Sucursal: SUC06, Producto: P127, Total Unidades: 1306, Total en pesos: $2379556.6599999997
Sucursal: SUC06, Producto: P128, Total Unidades: 638, Total en pesos: $1453396.5799999998
Sucursal: SUC06, Producto: P129, Total Unidades: 576, Total en pesos: $1845144.3399999999
Sucursal: SUC06, Producto: P130, Total Unidades: 789, Total en pesos: $1640184.0000000002

b) POR SUCURSAL: l informar el total comprado en unidades (TOTSUC) y el producto de
mayor (MYPROD, MYIMPOR) y menor compra (MNPRO,MNIMPOR) en pesos.

In [13]:
i = 0
n = len(compras_csv)
while i < n:
    Sucursal = compras_csv.loc[i, 'PRSUC']
    totsuc = 0
    MyPROD = 0
    Myimpor = 0
    MnProd = 0
    Mnimpor = 0

    while i < n and compras_csv.loc[i, 'PRSUC'] == Sucursal:
        Producto = compras_csv.loc[i, 'PRCOD']
        totuni = 0
        totimpor = 0

        while i < n and compras_csv.loc[i, 'PRSUC'] == Sucursal and compras_csv.loc[i, 'PRCOD'] == Producto:
            totuni += compras_csv.loc[i, 'PRCANT']
            totimpor += compras_csv.loc[i, 'PRCANT'] * compras_csv.loc[i, 'PRPRE']
            i += 1

        totsuc += totuni

        if totimpor > Myimpor:
            Myimpor = totimpor
            MyPROD = Producto
        elif totimpor < Mnimpor or MnProd == 0:
            Mnimpor = totimpor
            MnProd = Producto

    print(f"Sucursal: {Sucursal}, Total Unidades: {totsuc}")
    print(f"Producto más comprado: {MyPROD} con importe ${Myimpor}")
    print(f"Producto menos comprado: {MnProd} con importe ${Mnimpor}")

Sucursal: SUC01, Total Unidades: 46379
Producto más comprado: P131 con importe $3213342.73
Producto menos comprado: P134 con importe $320703.71
Sucursal: SUC02, Total Unidades: 33111
Producto más comprado: P106 con importe $2155968.909999999
Producto menos comprado: P137 con importe $101367.04
Sucursal: SUC03, Total Unidades: 49054
Producto más comprado: P129 con importe $3537428.3099999996
Producto menos comprado: P134 con importe $264632.85
Sucursal: SUC04, Total Unidades: 38526
Producto más comprado: P106 con importe $2545515.5199999996
Producto menos comprado: P137 con importe $181337.28999999998
Sucursal: SUC05, Total Unidades: 34125
Producto más comprado: P130 con importe $2295032.91
Producto menos comprado: P133 con importe $146891.51
Sucursal: SUC06, Total Unidades: 32702
Producto más comprado: P127 con importe $2379556.6599999997
Producto menos comprado: P135 con importe $210390.74
Sucursal: SUC07, Total Unidades: 46220
Producto más comprado: P107 con importe $3610906.9700000007
Producto menos comprado: P135 con importe $343268.04
Sucursal: SUC08, Total Unidades: 33906
Producto más comprado: P107 con importe $1927181.7099999995
Producto menos comprado: P134 con importe $148557.09000000003
Sucursal: SUC09, Total Unidades: 41544
Producto más comprado: P107 con importe $2875451.8700000006
Producto menos comprado: P134 con importe $209518.74999999994
Sucursal: SUC10, Total Unidades: 47805
Producto más comprado: P107 con importe $3603927.8200000008
Producto menos comprado: P132 con importe $180703.31

c) Por otro lado indicar a nivel total: total de sucursales del supermercado (CANSUC) y
compra total en pesos de todas las sucursales (TOTALIMP)

In [14]:
i = 0
n = len(compras_csv)

Cansuc = 0
totalimp = 0
tabla_sucursales = []

while i < n:
    Sucursal = compras_csv.loc[i, 'PRSUC']
    totsucursal = 0
    Cansuc += 1

    while i < n and compras_csv.loc[i, 'PRSUC'] == Sucursal:
        totsucursal += compras_csv.loc[i, 'PRCANT'] * compras_csv.loc[i, 'PRPRE']
        i += 1

    totalimp += totsucursal

    #print(f"Nombre de la sucursal: {Sucursal}, vendió: ${totsucursal}")
    tabla_sucursales.append([Sucursal, totsucursal,totalimp])
df_sucursales = pd.DataFrame(tabla_sucursales, columns=['Sucursal', 'Total en la sucursal', 'Total General'])

df_sucursales['Total en la sucursal'] = df_sucursales['Total en la sucursal'].apply(lambda x: f"${x:,.2f}")
df_sucursales['Total General'] = df_sucursales['Total General'].apply(lambda x: f"${x:,.2f}")
view_sucursales = df_sucursales.head(14)
view_sucursales

#print(f"Total de sucursales: {Cansuc}")
#print(f"Total general: ${totalimp}")

  Sucursal Total en la sucursal    Total General
0    SUC01       $59,217,588.75   $59,217,588.75
1    SUC02       $37,200,535.35   $96,418,124.10
2    SUC03       $60,866,598.71  $157,284,722.81
3    SUC04       $43,881,604.67  $201,166,327.48
4    SUC05       $40,775,913.21  $241,942,240.69
5    SUC06       $40,078,443.29  $282,020,683.98
6    SUC07       $59,225,193.60  $341,245,877.58
7    SUC08       $39,097,029.06  $380,342,906.64
8    SUC09       $53,322,446.16  $433,665,352.80
9    SUC10       $60,108,911.42  $493,774,264.22

In [15]:
compras_csv

      PRSUC PRCOD       PRFEC  PRPROV  PRCANT    PRPRE
0     SUC01  P100  2025-01-01  PROV02     116   246.97
1     SUC01  P100  2025-01-05  PROV13     103   255.53
2     SUC01  P100  2025-01-09  PROV04     112   254.78
3     SUC01  P100  2025-01-09  PROV04      63   262.24
4     SUC01  P100  2025-01-15  PROV03     101   254.72
...     ...   ...         ...     ...     ...      ...
9995  SUC10  P139  2025-09-25  PROV10       9   281.39
9996  SUC10  P139  2025-10-13  PROV12       2   279.03
9997  SUC10  P139  2025-10-14  PROV11       8   279.23
9998  SUC10  P139  2025-11-12  PROV03      12  4792.63
9999  SUC10  P139  2025-12-25  PROV13      11   274.76

[10000 rows x 6 columns]